### ISSUE TITLE
NSpanel color wheel script problem

### ISSUE THREAD

**Issue by nicoCRX** [ilyavolodin/NSPanel#1]
Hello,
I ve use your template to create my own interface for my NSpanel. Thank you for sharing your project.
I just have one problem : I don't understand this part:

```
  - platform: nextion
    name: $device_name Color Wheel
    page_id: 1
    component_id: 18
    internal: true
    on_release:
      then:
        - lambda: |-
            id(color_wheel_x).update();
            id(color_wheel_y).update();
        - delay: 20ms
        - lambda: |-
            RgbColor color = posToColor(id(color_wheel_x).state, id(color_wheel_y).state);
            id(selected_color_red) = String(color.r);
            id(selected_color_green) = String(color.g);
            id(selected_color_blue) = String(color.b);
        - homeassistant.service:
            service: script.set_light_rgb
            data:
              light_name: $target_lights
              red: !lambda 'return id(selected_color_red).c_str();'
              green: !lambda 'return id(selected_color_green).c_str();'
              blue: !lambda 'return id(selected_color_blue).c_str();'
```
You are calling a service script ? I have to create a script in my home assistant but with what elements ?

thx

**Comment by ilyavolodin** [comment]
Ah, yes, sorry, I forgot to check that script in. Problem is that ESPHome can't send an array of numbers to home assistant service, so you have to create a script that would accept those numbers as separate attributes. Here's the script:
```
alias: ESPHome RGB light set
sequence:
  - service: light.turn_on
    data_template:
      entity_id: '{{ light_name }}'
      rgb_color:
        - '{{ red }}'
        - '{{ green }}'
        - '{{ blue }}'
mode: single
```

**Comment by nicoCRX** [comment]
Ok. I'll try this
Thanks

**Comment by nicoCRX** [comment]
So I manage to send a color wheel info, but the script only receives (255-255-255), no matter where I press.
Where could I calibrate this X-Y information?
In nextion, in esphome code or in colorwheel.h file?
Thank you again for your help

**Comment by ckegels** [comment]
i tried this but it doesn't seem to work.
pretty new to all this so im very sorry.

i just added this to a script in home assistant but i dont seem to receive the values
(the script should be called set_light_rgb) right?

**Comment by ilyavolodin** [comment]
You could add some logging to the ESPHome script to see if you are getting back values from the C++ code, but other then that, it should work. Just heads up, I'm reasonably sure that there's a memory leak somewhere in C++ code, because NSPanel starts rebooting itself after a period of time when using this code. Unfortunately, I gave up on NSPanel and moved on to using Wink Relay instead, so I'm not planning on trying to fix it.

**Comment by ckegels** [comment]
Hi,
Thanks for the reply
Yea im putting in some loging now.
Yea the nextion is a royal pain in the ass, trying to get nextion and esphome to properly communicate with home assistant is just a bitch.


Lg

Christopher Kegels

**Comment by ckegels** [comment]
I seem to have multiple issues one being I only get 255 from all 3 rgb no other values, any clue where I went wrong?

Lg

Christopher Kegels

**Comment by ckegels** [comment]
So after adding logging and figuring out that the vallues werent correct (always 255) i was able to solve that however i still cant pass the values onto home assistant. pretty sure its a service/ script issue.
do i understand it correct that i just have to go into my scripts.yaml on home assistant and i can copy paste in your code ?
with a script name of set_light_rgb ?

**Comment by ckegels** [comment]
i seemed to have had an issue with using the yaml file.
made the automation in gui and than changed the vallues in yaml

now it works like a charm.
thank you good sir

**Comment by ilyavolodin** [comment]
Yeah, I haven't tried doing it in yaml files, but instead, just created a script in the UI.

**Comment by adrianGOO** [comment]
> alias: ESPHome RGB light set
> sequence:
>   - service: light.turn_on
>     data_template:
>       entity_id: '{{ light_name }}'
>       rgb_color:
>         - '{{ red }}'
>         - '{{ green }}'
>         - '{{ blue }}'
> mode: single

How did you resolve the issue with wheel?

I am stuck on RGB wheel and can not find the solution.

**Comment by ckegels** [comment]
can't remember exactly what i did, just remember it was something stupid with the ui/yaml it didnt work for me when just using the yaml but somehow doing it yaml and ui worked:

i hope the image helps

<img width="1420" alt="Screenshot 2022-12-10 at 00 23 19" src="https://user-images.githubusercontent.com/30844154/206811301-c299d33b-4758-4e51-afe3-1a428dcdb160.png">

**Comment by adrianGOO** [comment]
> can't remember exactly what i did, just remember it was something stupid with the ui/yaml it didnt work for me when just using the yaml but somehow doing it yaml and ui worked:
> 
> i hope the image helps
> 
> <img alt="Screenshot 2022-12-10 at 00 23 19" width="1420" src="https://user-images.githubusercontent.com/30844154/206811301-c299d33b-4758-4e51-afe3-1a428dcdb160.png">

I have already added the script but still nothing here, the wheel not changing the colours.
the dimmer and brightness controllers are working somehow but the wheel is not changing colours.

I am designing the panel for my needs but I am still missing the RGB controller to make it perfect for my room.

**Comment by ckegels** [comment]
dimmer/brightness are completely seperate from the color wheel,

ok so what i did when i couldnt figure this out is that i built some log debugging to try and find where the problem was.
i logged the vallues or red, green, blue in esphome etc


this is my code for the binary sensor, i added some logging (atleast i think i added it, maybe it was allready there)
```
#color wheel
  - platform: nextion
    name: $device_name Color Wheel
    page_id: 6
    component_id: 13
    internal: true
    on_press:
      then:
        - script.stop: my_timer
    on_release:
      then:
        - lambda: |-
            id(color_wheel_x).update();
            id(color_wheel_y).update();
        - delay: 20ms
        - lambda: |-
            RgbColor color = posToColor(id(color_wheel_x).state, id(color_wheel_y).state);
            id(selected_color_red2) = String(color.r);
            id(selected_color_green2) = String(color.g);
            id(selected_color_blue2) = String(color.b);
        - logger.log:
            format: "RGB RED VALUE: %s"
            args: [ 'id(selected_color_red2).c_str()']
        - logger.log:
            format: "RGB GREEN VALUE: %s"
            args: [ 'id(selected_color_green2).c_str()']
        - logger.log:
            format: "RGB BLUE VALUE: %s"
            args: [ 'id(selected_color_blue2).c_str()']
        - homeassistant.service:
            service: script.set_light_rgb
            data:
              light_name: $target_lights
              red: !lambda 'return id(selected_color_red2).c_str();'
              green: !lambda 'return id(selected_color_green2).c_str();'
              blue: !lambda 'return id(selected_color_blue2).c_str();'
        - script.execute: my_timer

```

**Comment by ckegels** [comment]
you didnt forget to add the colorwheel file to the esphome root directory right?

**Comment by adrianGOO** [comment]
same script here but not responding.

![image](https://user-images.githubusercontent.com/11524611/206814842-0cd6e526-bc12-474e-94a6-7bcf76293048.png)


> #color wheel
>   - platform: nextion
>     name: $device_name Color Wheel
>     page_id: 6
>     component_id: 13
>     internal: true
>     on_press:
>       then:
>         - script.stop: my_timer
>     on_release:
>       then:
>         - lambda: |-
>             id(color_wheel_x).update();
>             id(color_wheel_y).update();
>         - delay: 20ms
>         - lambda: |-
>             RgbColor color = posToColor(id(color_wheel_x).state, id(color_wheel_y).state);
>             id(selected_color_red2) = String(color.r);
>             id(selected_color_green2) = String(color.g);
>             id(selected_color_blue2) = String(color.b);
>         - logger.log:
>             format: "RGB RED VALUE: %s"
>             args: [ 'id(selected_color_red2).c_str()']
>         - logger.log:
>             format: "RGB GREEN VALUE: %s"
>             args: [ 'id(selected_color_green2).c_str()']
>         - logger.log:
>             format: "RGB BLUE VALUE: %s"
>             args: [ 'id(selected_color_blue2).c_str()']
>         - homeassistant.service:
>             service: script.set_light_rgb
>             data:
>               light_name: $target_lights
>               red: !lambda 'return id(selected_color_red2).c_str();'
>               green: !lambda 'return id(selected_color_green2).c_str();'
>               blue: !lambda 'return id(selected_color_blue2).c_str();'
>         - script.execute: my_timer

No it is already there 

![image](https://user-images.githubusercontent.com/11524611/206817927-2c93d14f-c7da-40ea-9944-af4d6af5ea2d.png)

**Comment by ckegels** [comment]
> same script here but not responding.
> 
> ![image](https://user-images.githubusercontent.com/11524611/206814842-0cd6e526-bc12-474e-94a6-7bcf76293048.png)
> 
> > #color wheel
> > 
> > * platform: nextion
> >   name: $device_name Color Wheel
> >   page_id: 6
> >   component_id: 13
> >   internal: true
> >   on_press:
> >   then:
> >   - script.stop: my_timer
> >   on_release:
> >   then:
> >   - lambda: |-
> >   id(color_wheel_x).update();
> >   id(color_wheel_y).update();
> >   - delay: 20ms
> >   - lambda: |-
> >   RgbColor color = posToColor(id(color_wheel_x).state, id(color_wheel_y).state);
> >   id(selected_color_red2) = String(color.r);
> >   id(selected_color_green2) = String(color.g);
> >   id(selected_color_blue2) = String(color.b);
> >   - logger.log:
> >   format: "RGB RED VALUE: %s"
> >   args: [ 'id(selected_color_red2).c_str()']
> >   - logger.log:
> >   format: "RGB GREEN VALUE: %s"
> >   args: [ 'id(selected_color_green2).c_str()']
> >   - logger.log:
> >   format: "RGB BLUE VALUE: %s"
> >   args: [ 'id(selected_color_blue2).c_str()']
> >   - homeassistant.service:
> >   service: script.set_light_rgb
> >   data:
> >   light_name: $target_lights
> >   red: !lambda 'return id(selected_color_red2).c_str();'
> >   green: !lambda 'return id(selected_color_green2).c_str();'
> >   blue: !lambda 'return id(selected_color_blue2).c_str();'
> >   - script.execute: my_timer
> 
> No it is already there
> 
> ![image](https://user-images.githubusercontent.com/11524611/206817927-2c93d14f-c7da-40ea-9944-af4d6af5ea2d.png)

so the vallues are showing in the logger?

**Comment by adrianGOO** [comment]
To tell you the truth I am trying to integrate it  to the EU version so I am suspecting that I am missing any point that is confusing me because this is the first week I am using ESPHome with Nextion editor.
Every code I have used is copy paste in combination with my logic  :(

![image](https://user-images.githubusercontent.com/11524611/206818282-13c5edb7-266b-483c-9fa2-1155899c61a2.png)
```
######################################################
substitutions:
  # Name the device and it's entities
  device_name: nspanel-dev
  wifi_ssid: !secret wifi_ssid
  wifi_pass: !secret wifi_password
  tft_url: !secret tft_upload_url
  target_lights: light.room_lamp_rgb

# global varibles.
globals:
  - id: selected_color_red
    type: String
  - id: selected_color_green
    type: String
  - id: selected_color_blue
    type: String

############Binary#############
### RGB CONTROLER ##################

  - platform: nextion
    name: $device_name Brightness Slider
    page_id: 9
    component_id: 2
    internal: true
    on_release:
      then:
        - lambda: !lambda |-
            id(brightness_value).update();
  
  - platform: nextion
    name: $device_name Color Wheel
    page_id: 9
    component_id: 17
    internal: true
    on_release:
      then:
        - lambda: |-
            id(color_wheel_x).update();
            id(color_wheel_y).update();
        - delay: 20ms
        - lambda: |-
            RgbColor color = posToColor(id(color_wheel_x).state, id(color_wheel_y).state);
            id(selected_color_red) = String(color.r);
            id(selected_color_green) = String(color.g);
            id(selected_color_blue) = String(color.b);
        - homeassistant.service:
            service: script.yeelight_hsv_mode
            data:
              light_name: $target_lights
              red: !lambda 'return id(selected_color_red).c_str();'
              green: !lambda 'return id(selected_color_green).c_str();'
              blue: !lambda 'return id(selected_color_blue).c_str();'
              
  - platform: nextion
    name: $device_name Color Temp Slider
    page_id: 9
    component_id: 12
    internal: true

######### RGB SENSOR ##################
########################################
  - platform: homeassistant
    id: current_brightness
    entity_id: $target_lights
    attribute: brightness
    on_value:
      then:
        - lambda: 'id(disp1).send_command_printf("brightnessVal.val=%i", (int)x);'
        
  - platform: homeassistant
    id: current_color_temp
    entity_id: $target_lights
    attribute: color_temp
    on_value:
      then:
        - lambda: 'id(disp1).send_command_printf("tempSlider.val=%i", (int)x);'
        
  - platform: nextion
    id: brightness_value
    component_name: brightnessVal
    on_value:
      then:
        - homeassistant.service:
            service: light.turn_on
            data:
              entity_id: $target_lights
              brightness: !lambda 'return (int)x;'
            
  - platform: nextion
    id: color_temp_value
    component_name: tempSlider
    on_value:
      then:
        - homeassistant.service:
            service: light.turn_on
            data:
              entity_id: $target_lights
              color_temp: !lambda 'return (int)x;'

  - platform: nextion
    id: color_wheel_x
    component_name: selectedColorX
    filters:
      - offset: -27
            
  - platform: nextion
    id: color_wheel_y
    component_name: selectedColorY
    filters:
      - offset: -91
    on_release:
      then:
        - lambda: !lambda |-
            id(color_temp_value).update();
```

> its just a timer to turn off the display

Do I have to create a timer because I not using any timer?

**Comment by ckegels** [comment]
> To tell you the truth I am trying to integrate it to the EU version so I am suspecting that I am missing any point that is confusing me because this is the first week I am using ESPHome with Nextion editor. Every code I have used is copy paste in combination with my logic :(
> 
> ![image](https://user-images.githubusercontent.com/11524611/206818282-13c5edb7-266b-483c-9fa2-1155899c61a2.png) ###################################################### substitutions:
> 
> # Name the device and it's entities
> device_name: nspanel-dev wifi_ssid: !secret wifi_ssid wifi_pass: !secret wifi_password tft_url: !secret tft_upload_url target_lights: light.room_lamp_rgb
> 
> # global varibles.
> globals:
> 
> * id: selected_color_red
>   type: String
> * id: selected_color_green
>   type: String
> * id: selected_color_blue
>   type: String
> 
> ############Binary#############
> 
> ### RGB CONTROLER
> * platform: nextion
>   name: $device_name Brightness Slider
>   page_id: 9
>   component_id: 2
>   internal: true
>   on_release:
>   then:
>   - lambda: !lambda |-
>   id(brightness_value).update();
> * platform: nextion
>   name: $device_name Color Wheel
>   page_id: 9
>   component_id: 17
>   internal: true
>   on_release:
>   then:
>   - lambda: |-
>   id(color_wheel_x).update();
>   id(color_wheel_y).update();
>   - delay: 20ms
>   - lambda: |-
>   RgbColor color = posToColor(id(color_wheel_x).state, id(color_wheel_y).state);
>   id(selected_color_red) = String(color.r);
>   id(selected_color_green) = String(color.g);
>   id(selected_color_blue) = String(color.b);
>   - homeassistant.service:
>   service: script.yeelight_hsv_mode
>   data:
>   light_name: $target_lights
>   red: !lambda 'return id(selected_color_red).c_str();'
>   green: !lambda 'return id(selected_color_green).c_str();'
>   blue: !lambda 'return id(selected_color_blue).c_str();'
> * platform: nextion
>   name: $device_name Color Temp Slider
>   page_id: 9
>   component_id: 12
>   internal: true
> 
> ######### RGB SENSOR ################## ########################################
> 
> * platform: homeassistant
>   id: current_brightness
>   entity_id: $target_lights
>   attribute: brightness
>   on_value:
>   then:
>   - lambda: 'id(disp1).send_command_printf("brightnessVal.val=%i", (int)x);'
> * platform: homeassistant
>   id: current_color_temp
>   entity_id: $target_lights
>   attribute: color_temp
>   on_value:
>   then:
>   - lambda: 'id(disp1).send_command_printf("tempSlider.val=%i", (int)x);'
> * platform: nextion
>   id: brightness_value
>   component_name: brightnessVal
>   on_value:
>   then:
>   - homeassistant.service:
>   service: light.turn_on
>   data:
>   entity_id: $target_lights
>   brightness: !lambda 'return (int)x;'
> * platform: nextion
>   id: color_temp_value
>   component_name: tempSlider
>   on_value:
>   then:
>   - homeassistant.service:
>   service: light.turn_on
>   data:
>   entity_id: $target_lights
>   color_temp: !lambda 'return (int)x;'
> * platform: nextion
>   id: color_wheel_x
>   component_name: selectedColorX
>   filters:
>   
>   * offset: -27
> * platform: nextion
>   id: color_wheel_y
>   component_name: selectedColorY
>   filters:
>   
>   * offset: -91
>     on_release:
>     then:
>     
>     * lambda: !lambda |-
>       id(color_temp_value).update();

you added in the extra line in the editor for the eu version if i remember corretly you have to add something, i dont actuelly use a ns panel so i am not sure (i use a nextion display with esp32)

**Comment by adrianGOO** [comment]
Yes you are right I added extra page that I exported from yliavolodin HMI and imported to EU version HMI.

**Comment by ckegels** [comment]
what is that on release at the end? it seems very out of place,
btw don't worry about not understanding it, neither do i. and i am very aware i am not the right person to help but i will try.
i myself started my project by copy pasting and adding code to that. after a while you will be able to make your own things.

**Comment by ckegels** [comment]
> Yes you are right I added extra page that I exported from yliavolodin HMI and imported to EU version HMI.

the extra line in the program.s

but please try to start the display and tap arround on the colorwheel you need to figure out if the esphome is even getting color vallues and check the logs for these (make sure they are not all the same)

**Comment by adrianGOO** [comment]
> what is that on release at the end? it seems very out of place, btw don't worry about not understanding it, neither do i. and i am very aware i am not the right person to help but i will try. i myself started my project by copy pasting and adding code to that. after a while you will be able to make your own things.

you mean this part?

**offset: -27**
platform: nextion
id: color_wheel_y
component_name: selectedColorY
filters:

**offset: -91**
on_release:
then:

I tried also without minus also with minus but still same. Sometimes when I am not sure what I am doind I simply try every option heheheh

**Comment by ckegels** [comment]
> > what is that on release at the end? it seems very out of place, btw don't worry about not understanding it, neither do i. and i am very aware i am not the right person to help but i will try. i myself started my project by copy pasting and adding code to that. after a while you will be able to make your own things.
> 
> you mean this part?
> 
> **offset: -27** platform: nextion id: color_wheel_y component_name: selectedColorY filters:
> 
> **offset: -91** on_release: then:
> 
> I tried also without minus also with minus but still same. Sometimes when I am not sure what I am doind I simply try every option heheheh

yea what is the on release doing there? its a sensor not a binary sensor, to me that seems wrong. why is it there?
where does it come from?


also please format your code correctly on here, i cant tell if spacing is wrong, because yes that matters.

**Comment by ckegels** [comment]
> To tell you the truth I am trying to integrate it to the EU version so I am suspecting that I am missing any point that is confusing me because this is the first week I am using ESPHome with Nextion editor. Every code I have used is copy paste in combination with my logic :(
> 
> ![image](https://user-images.githubusercontent.com/11524611/206818282-13c5edb7-266b-483c-9fa2-1155899c61a2.png) ###################################################### substitutions:
> 
> # Name the device and it's entities
> device_name: nspanel-dev wifi_ssid: !secret wifi_ssid wifi_pass: !secret wifi_password tft_url: !secret tft_upload_url target_lights: light.room_lamp_rgb
> 
> # global varibles.
> globals:
> 
> * id: selected_color_red
>   type: String
> * id: selected_color_green
>   type: String
> * id: selected_color_blue
>   type: String
> 
> ############Binary#############
> 
> ### RGB CONTROLER
> * platform: nextion
>   name: $device_name Brightness Slider
>   page_id: 9
>   component_id: 2
>   internal: true
>   on_release:
>   then:
>   - lambda: !lambda |-
>   id(brightness_value).update();
> * platform: nextion
>   name: $device_name Color Wheel
>   page_id: 9
>   component_id: 17
>   internal: true
>   on_release:
>   then:
>   - lambda: |-
>   id(color_wheel_x).update();
>   id(color_wheel_y).update();
>   - delay: 20ms
>   - lambda: |-
>   RgbColor color = posToColor(id(color_wheel_x).state, id(color_wheel_y).state);
>   id(selected_color_red) = String(color.r);
>   id(selected_color_green) = String(color.g);
>   id(selected_color_blue) = String(color.b);
>   - homeassistant.service:
>   service: script.yeelight_hsv_mode
>   data:
>   light_name: $target_lights
>   red: !lambda 'return id(selected_color_red).c_str();'
>   green: !lambda 'return id(selected_color_green).c_str();'
>   blue: !lambda 'return id(selected_color_blue).c_str();'
> * platform: nextion
>   name: $device_name Color Temp Slider
>   page_id: 9
>   component_id: 12
>   internal: true
> 
> ######### RGB SENSOR ################## ########################################
> 
> * platform: homeassistant
>   id: current_brightness
>   entity_id: $target_lights
>   attribute: brightness
>   on_value:
>   then:
>   - lambda: 'id(disp1).send_command_printf("brightnessVal.val=%i", (int)x);'
> * platform: homeassistant
>   id: current_color_temp
>   entity_id: $target_lights
>   attribute: color_temp
>   on_value:
>   then:
>   - lambda: 'id(disp1).send_command_printf("tempSlider.val=%i", (int)x);'
> * platform: nextion
>   id: brightness_value
>   component_name: brightnessVal
>   on_value:
>   then:
>   - homeassistant.service:
>   service: light.turn_on
>   data:
>   entity_id: $target_lights
>   brightness: !lambda 'return (int)x;'
> * platform: nextion
>   id: color_temp_value
>   component_name: tempSlider
>   on_value:
>   then:
>   - homeassistant.service:
>   service: light.turn_on
>   data:
>   entity_id: $target_lights
>   color_temp: !lambda 'return (int)x;'
> * platform: nextion
>   id: color_wheel_x
>   component_name: selectedColorX
>   filters:
>   
>   * offset: -27
> * platform: nextion
>   id: color_wheel_y
>   component_name: selectedColorY
>   filters:
>   
>   * offset: -91
>     on_release:
>     then:
>     
>     * lambda: !lambda |-
>       id(color_temp_value).update();

i noticed your code has no debugging please look at the code i posted and add that in to see the rgb vallues

**Comment by adrianGOO** [comment]
What code you are using on our script my_timer?

**Comment by ckegels** [comment]
its just a timer to turn off the display

**Comment by ckegels** [comment]
also just checking but you didnt forget to add the includes right?

```
esphome:
  name: $device_name
  includes:
    - colorwheel.h
```

**Comment by adrianGOO** [comment]
> also just checking but you didnt forget to add the includes right?
> 
> ```
> esphome:
>   name: $device_name
>   includes:
>     - colorwheel.h
> ```
yes they are added also 


```
# Example config.yaml
esphome:
  name: nspanel
  comment: $device_name
  includes:
    - colorwheel.h
```
